version: '3'
services:
  goat1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - CONFIG=./docker/config1.json
      - KEYSTORE=./docker/keystore1.json
    restart: always
    ports:
      - 3000:3000
  goat2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - CONFIG=./docker/config2.json
      - KEYSTORE=./docker/keystore2.json
    restart: always
  goat3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - CONFIG=./docker/config3.json
      - KEYSTORE=./docker/keystore3.json
    restart: always