version: '3'
services:
  goat1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
  goat2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  goat3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always